### ISSUE TITLE
How should generate bundle behave with existing bundle metadata?

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#37] opened 2019-03-20 11:01 UTC
`generate bundle` currently tries to do some clever merging if you run it in a directory with an existing bundle.   
I think the main usecase for this command is generating a new bundle.  You might run it in a directory with an existing bundle by accident and get strange results.
So my feeling is that the default behaviour should be to fail if there's existing bundle metadata, and provide an option to add a new bundlepart.

**Comment by pcoop** [comment] 2019-03-20 18:02
I suspect a common usage pattern will be:

1) Run Generate Bundle
2) Realise the default NODEJSAPP name is rubbish
3) Rerun Generate Bundle specifying a better NODEJSAPP name

The current implementation is that at step 3 we merge the new NODEJSAPP into the existing manifest, resulting in a Bundle with 2 NODEJSAPPs defined in it (probably sharing the same implementation). Almost certainly not what was intended.

So while merge is a nice feature, I agree that it makes more sense to opt-in to it and fail by default. See also issue #27 which relates to the overwrite processing for DEPLOY, we should attempt to be consistent in whatever course we take. We might want three options: fail, overwrite/replace, or merge.

**Comment by matthewpwilson** [comment] 2019-03-21 11:37
Design meeting notes:
fail if cics.xml exists already
--overwrite will start again (does it remove both manfiest and generated profile?) - details TBD
--merge will add a new bundle part

**Comment by matthewpwilson** [comment] 2019-04-04 12:02
This is almost there with #51. However, when specifying `--merge` we currently require to specify `--overwrite` as well. I think these are two logically distinct operations - either we merge new content into the exist manifest, or we replace it.   The user doesn't care whether we actually update the manifest on disk or overwrite it with a new version containing the merge content. So I think `--merge` should work by itself.

**Comment by pcoop** [comment] 2019-04-24 12:48
It seems to me that --merge is a subset of --overwrite; it's a scenario in which the user accepts that their bundle will change, but they want as much of their existing meta-data to survive as possible. Whereas a regular --overwrite will destroy the existing meta-data.

This distinction becomes important when we consider the following two commands:

1) zowe cics-deploy generate bundle --merge
2) zowe cics-deploy generate bundle --merge --overwrite false

We can't programmatically distinguish between 1) and 2), in both cases the handler is informed that --overwrite is set to false. If we implement logic to have --merge imply --override then that's okay in case 1) but less so for case 2). The second user seems to want --merge to preserve all of their existing meta-data as-is, but that's not something the tool can commit to achieving. We could issue a warning message and then proceed to potentially splat their existing data anyway, but that's not very nice. It seems better to issue an error message and force them to be clear about their intentions.

We could take a completely different approach and combine --merge and --overwrite into a single three state parameter, but I rather like having --overwrite sharing the same semantic meaning across 'bundle generate', 'bundle push' and 'profiles update'. Or we could change the implementation so that --merge is guaranteed not to replace existing similarly named meta-data, but that will involve quite a few changes and new error conditions. I'm inclined to keep things as is.

**Comment by markcocker** [comment] 2019-05-03 08:34
Assigning to @matthewpwilson to consider if the changes in #51 and #119 resolve this.

**Comment by matthewpwilson** [comment] 2019-05-15 13:24
Triage: Update CLI help to relfect current behaviour

**Closed as completed** 2019-05-31 12:22 UTC
Labels: enhancement
