### ISSUE TITLE
Update dependencies to @zowe

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#48] opened 2019-03-22 10:38 UTC
A recent commit on Zowe CLI changed the prefix for both `core` and `imperative` to `@zowe` instead of `@brightside`.
We'll need to update all our dependencies and imports to reflect this.

Incidentally, I think this was the root of the issues we had with importing Session/AbstractSession.

**Comment by matthewpwilson** [comment] 2019-03-22 16:04
Jenkins will probably need updating to install Zowe core from @zowe instead of @brightside too

**Comment by markcocker** [comment] 2019-03-22 16:37
Will this change mean the cics-deploy plugin will require a minimum version of the Zowe CLI?

**Comment by matthewpwilson** [comment] 2019-03-22 16:57
Yes. But we'll need a higher version for push in order to prereq the ssh and file upload support we'll be adding.

**Comment by pcoop** [comment] 2019-03-28 11:44
I've tried to have a go at this, but I don't think zowe is ready for this yet.

The first issue is that @zowe/core seems not to be available yet: @zowe/imperative and @zowe/cli are both there, but core isn't. That leaves us with a mix of both @zowe and @brightside simultaneously.

The second issue is that I get a ton of typescript errors whenever I issue a build reporting things like:

node_modules/@zowe/imperative/lib/utilities/src/TextUtils.d.ts:14:42 - error TS1039: Initializers are not allowed in ambient contexts: static readonly DEFAULT_WRAP_WIDTH = 80;

Their source seems not to be compatible with the typescript validator we're using.

**Comment by pcoop** [comment] 2019-03-28 13:19
Okay, so the second problem turned out to be the version of typescript we'd registered in package.json; I've updated it to a newer level and the error messages went away. Problem solved... except moving to a newer version of zowe causes weird things to happen with respect to the app logging - informational trace data now gets logged to the console. That's not good.

**Comment by pcoop** [comment] 2019-03-28 15:24
The logging problem seems to be caused by changes to Imperative initialisation - it's not being initialised automatically. Adding an explicit call to Imperative.init() fixes things... except that it causes the unit tests to go bonkers. Vast amounts of garbage is dumped to the console when the tests run. I've ended up with an unpleasant compromise - I pass a flag in from the caller (the unit test handler) to request silent mode, and thereby avoid initialising Imperative from the unit tests. That seems to work.

But then there's *another* issue. If we throw an ImperativeError out of the handler then zowe cli now reports: "Unexpected Command Error: Please review the message and stack below.
**Contact the creator of handler: "C:\temp\zowe\cics\zowe-cli-cics-deploy-plugin\lib\cli\deploy\bundle/DeployBundle.handler"**". Throwing an ImperativeError was the only mechanism we'd found for returning a non-zero return code, returning to rc=0 even in error cases will be unpleasant.

**Comment by pcoop** [comment] 2019-03-28 16:26
I've found an alternative way to set a response code by setting process.exitCode; that sets a code that will be used at process exit if nothing replaces it. It seems to play nicely with the test-suites, it's a viable alternative to throwing an ImperativeError from the handler. But... this change involves significant reworking of the unit tests, loads of tests currently expect to receive an exception and need some other mechanism to check their output. A good number of them also mock the filesystem in such a way that snapshot testing can't be relied upon to work. Ugh.

**Comment by matthewpwilson** [comment] 2019-04-02 10:05
re: @zowe/core - see https://github.com/zowe/zowe-cli/pull/280 - sounds like @zowe/cli has replaced @brightside/core

**Closed as completed** 2019-04-04 12:25 UTC
Labels: bug
